---
- hosts: ukg
  become: true
  tasks:
  - name: deploying sample code
    copy: src=/etc/ansible/playbook/index.html dest=/var/www/html/
  - name: restarting httpd
    service: name=httpd state=restarted
